### ISSUE TITLE
Weather forecasts

### ISSUE THREAD

**Issue by rumanbeen** [ttt246/RisingBrain#14]
I typed "help"' & got a response. I typed " tell me about today's weather forecasts". I got this answer " I am sorry, I don't have access to real-time weather information." It was tested on Google Pixel 3. BUILD ID: 1.5 Build 1, uploaded by 29-05-2023

Here is a short video of how it responded.

https://www.loom.com/share/7ceb0704dd7c48b5bc1bcbb942ed3afa

**Comment by stackdev37** [comment]
The model of openai is not answering this kind of question (tell me about today's weather forecasts". 
We should develop this new feature as a agent to get achieved the tasks on something .. more likely AutoGPT. 

It should be new story. We did not develop it yet. 

**It takes around 3 ~ 4 days based on AutoGPT.** 

To: @tukpsyche @rumanbeen 
Cc: @posix4e @peterluo3131

**Comment by tukpsyche** [comment]
added feature request: https://github.com/ttt246/RisingPhone/issues/9
