### ISSUE TITLE
show me a picture of a smartphone

### ISSUE THREAD

**Issue by rumanbeen** [ttt246/RisingBrain#15]
The app opens up with no errors, glitches, lag. But I typed "show me a picture of a smartphone" but I got an answer like this " I'm sorry, as an AI language model, I don't have the ability to display images. However, you can search for images of smartphones on any search engines or image database like Google images or Shutterstock."  The tested device was Motorola Moto G7

BUILD ID: 1.5 Build 1, uploaded by 29-05-2023
 Here is a short video of how it responded.

https://www.loom.com/share/ed46d39ca9364b6588dc74c40f1a55f0

**Comment by stackdev37** [comment]
It is a same story with #25
